### ISSUE TITLE
skeletal animation support (+questions)

### ISSUE THREAD

**Issue by shakesoda** [bjornbytes/lovr#17]
I had a look through the API and I can't tell if the appropriate data (bones, weights etc) is available from loaded `Model`s, and there's no `Data` object like I use with love for IQM, so I can't use [this](https://github.com/excessive/iqm) without making it build tables instead.

Also, is it possible to set all the matrix values manually in a `Transform` object? looks like I'd need to do this when sending matrices to shaders for stuff like shadow mapping... which also needs support for render targets, which appear to be absent.

**Comment by bjornbytes** [comment]
Support for skeletal animation is in progress.  I'm still working out the API, if you have any thoughts or input that would be appreciated since it seems like you've got some experience here.

I'm interested in adding the `*Data` objects, I haven't gotten around to it yet though.  They've always been a bit lower in priority since they're a somewhat advanced feature.

You can't set the values of a `Transform` manually right now, which is really weird.  I'll add that in, thanks for pointing it out!  I think you can also send 16 values for the mat4 in a table, but that's not always convenient.

Render targets exist but the API is dated and not great.  You can pass a width and height instead of a filename into `lovr.graphics.newTexture` to get something like a Canvas (with a depth buffer) and you can call `:renderTo` on it.

**Comment by bjornbytes** [comment]
Animations are in master now, going to close this

**Comment by shakesoda** [comment]
awesome, will make some time to try it out soon
