### ISSUE TITLE
New filesystem module is not threadsafe

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#196]
There are no locks or other thread awareness on the `state` structure in the new filesystem.c. Problems that could occur include

* One thread is calling lovrFilesystemIsFile while another is calling lovrFilesystemMount.
* Two threads call lovrFilesystemMount at once.
* Two threads call setRequirePath at once.

Come to think of it, does it even make sense for the filesystem state to be global across all threads? That is, if one thread changes the require path or mounts a new path, *should* it change for other threads also? Maybe each thread should have its own fs state, inherited from the thread that spawned it.

I think this should be fixed before 0.14 because i can imagine ways it should lead to a crash. If it is not fixed it should DEFINITELY be documented (and whatever the behavior is on the filesystem mounts/requires being shared or not shared is, that should be documented).

**Comment by mcclure** [comment]
Oh, small thought: This would be an excellent use case for a read-write lock

**Comment by bjornbytes** [comment]
This was an intentional decision made to simplify the design of the implementation.  To me it seems like the common case is that configuring the require path and mounting archives is a one-time or few-time setup operation that is often done on the main thread.  Of course, if it consistently causes problems for people then it can be improved.  I can document this behavior as part of the process of updating the documentation for the next release.

Currently in LÖVR all modules can only be initialized by a single thread and will always be destroyed by the thread that initialized them.  Thread-local data is used for a few situations where threads each need their own copy of something.  I can sorta see an argument for making the require path thread-local because `package.path` is unique to each Lua state but on the other hand I kinda like it when require "just works" and it could get annoying to set that up for each new thread separately.  I also think it would be confusing if each thread had its own set of archives or its own save directory.

**Comment by mcclure** [comment]
I don't know if that's reasonable or not but: If that is the system design, we could still be doing more to protect the user. What if as soon as a second thread is created, a flag state.filesystemFreeze is set, and any attempt to call a filesystem.c mutator method after that results in an error? We could also add a conf setting to disable the safety check if there's someone who "knows what they're doing". This would protect users from a seriously dangerous and difficult-to-debug gotcha, but have no more perf impact than one branch per filesystem op.

**Comment by bjornbytes** [comment]
Planning to make core/ref a general atomics thing, move refcounting-specific stuff into util, and then use compare exchange to make filesystem threadsafe.

**Comment by bjornbytes** [comment]
Actually -- I don't think it's valuable enough to support this, given the overhead/effort of the implementation.  The intended use case is to configure the virtual filesystem at startup before performing filesystem operations on multiple threads.  I updated the docs to call this out.

**Comment by mcclure** [comment]
I think as long as it's documented it's probably okay.
