### ISSUE TITLE
lovr.timer.getTime only changes at updates on Oculus Mobile.

### ISSUE THREAD

**Issue by porglezomp** [bjornbytes/lovr#212]
I was trying to implement a rough CPU timer with `lovr.timer.getTime()` as a first pass and was constantly getting 0. It seems like it's set to only change at events. This should at least be documented, and preferably be changed to give a live version of the time if possible (although it's currently doing stuff to handle pausing and things, so I imagine there's a good reason it is the way it is that I'm not aware of).

**Comment by bjornbytes** [comment]
Hm, that seems bad.  It's returning the headset's predicted display time and using that as the implementation of getTime in the platform layer (which is what `lovr.timer.getTime` queries).  The headset interface has a separate `getDisplayTime` function where the predicted display time is meant to be returned.

I don't fully understand the pause stuff going on but maybe this could be tracked as an "epoch" that is separate from the various timers?  cc @mcclure for more info, I think the pause stuff was tricky/buggy and interacts with android lifecycle stuff...

**Comment by mcclure** [comment]
This… was… me misunderstanding what lovr.timer.getTime was supposed to do, I think.

The complicated pausing stuff is MOSTLY to work around a particular nasty OS bug from early in the Oculus Go's lifespan. That bug has since been fixed so I can simplify the pause logic now. 

Here is a question: Say you pause the app, and then you resume it 20 seconds later (ie you go to the main menu, and then you return). Should lovr.timer.getTime() indicate 20 seconds passed?

If you're basing dynamics on lovr.timer.getTime(), a jump of 20 seconds could make you do… bad things.

**Comment by bjornbytes** [comment]
I think it would advance by 20 seconds because `timer.getTime` is supposed to be wallclock time.  But maybe you could hook into `lovr.focus` events to detect when the pauses happen if you need to stop your game's timers?  Hm

**Comment by bjornbytes** [comment]
It's going to be challenging to emit focus events on android because if we were to `lovrEventPush(EVENT_FOCUS, false)` when android tells us we are paused, no Lua code would be around to poll that event until after resuming...

**Comment by bjornbytes** [comment]
The thing I want to do here is:

- lovr.timer.getTime returns wallclock time on android/oculus_mobile
- When the android activity is paused/resume, focus events are emitted.  Due to the structure of the android main loop and the Lua coroutine, both of these events will be consumed after the activity is resumed.  This is just going to be documented as a quirk/known limitation of the design.
- To avoid huge `dt` values after resuming, when the android activity is resumed it will ping the timer module and tell it to reset the delta.

**Comment by shakesoda** [comment]
@bjornbytes i'd make sure to use the headset predicted time for the deltas passed to update when available, it's a lot more consistent (iirc, oculus documentation even specifically recommends doing this) than regular wall clock will be

**Comment by bjornbytes** [comment]
There is `lovr.headset.getTime` that returns the display time, but the default run loop hasn't been converted to use it yet.  It makes sense for animation and stuff but I haven't been able to grok if it's okay to use for things like physics timesteps whatnot (you'd probably want a separate fixed timestep or something).  Either way, it's a separate issue from this one.

**Comment by mcclure** [comment]
I think you want to use predicted-frame-time for deltas. The point of the update function is to prepare a frame for display. Actual wallclock time is something that would be good to expose but it's only useful for certain special applications.

Fixed physics timesteps are for many purposes a good feature but the user Lua code can emulate it itself by looking at the dt and saying "oh that's 30 ms, run my physics timestep function 3 times). The only reason I see for Lovr getting involved in providing a fixed timestep event is so the user can do work "between frames" instead of leaving the CPU idle. However in order for this to be useful we would have to be already meeting and beating our deadlines consistently (such the CPU is idle in the first place)… is that the case in practice now?

Not sure this is clear but the predicted display time *currently* freezes while the application is suspended on Android.
