### ISSUE TITLE
Explicitly specify both draw syle (line/fill) and color in call.

### ISSUE THREAD

**Issue by aiverson** [bjornbytes/lovr#214]
Needing to call the setColor function to set a color and then call the draw call with the "line" drawstyle is a source of needless extra bugs and complexity. It adds an additional round trip across the CAPI boundary and makes bugs involving forgetting to reset the global state more likely.

Reading the code suggests there is currently no way to provide a material (or otherwise) that specifies color information to a call using "line" drawstyle. Is this correct? Is there a way to do this? Should there be a way to do this?

**Comment by bjornbytes** [comment]
It's true, right now using a Material instead of a DrawStyle forces the "fill" style.  I think this is because usually materials are/were used for texturing and shading, where having a filled shape with a surface is desired.

Using a Mesh would be a way to work around this and also get better performance, but it is likely going to be cumbersome to set up.  Whether that would be a worthwhile tradeoff depends on the project.

It would be possible to modify the API for primitive function variants that accept materials to also accept a draw style, but this also complicates the bindings a bit and forces people going through the supposedly common path to supply an extra "redundant" argument.  So I'm kind of lukewarm on it, especially when setColor can already be used here.
