### ISSUE TITLE
If lovr.update is slow, lovr.audio.setPose() will conflict with default loop's setPose and create distorted audio

### ISSUE THREAD

**Issue by nevyn** [bjornbytes/lovr#253]
If I move the listener in lovr.update, and my update function is slow, it seems that the audio jumps between headset location and my inputted location rapidly :S

maybe the audio module should store the listener location at the beginning of the loop, and only set it at the end of the loop, so that user-inputted position is the one that is actually applied to OpenAL :S otoh that'd introduce some positional audio lag... Not sure what the best solution is :S

# Repro

```

function lovr.load()
    sound = lovr.audio.newSource("bwomp.ogg", "static")
    matrix = lovr.math.newMat4(
        lovr.math.vec3(-2, 0, 0)
    )
end

function lovr.update(dt)
    if sound:isPlaying() == false then
        sound:play()
    end
    lovr.timer.sleep(0.05)
    lovr.audio.setPose(matrix:unpack())
end
```

Then turn around until the hard-coded offset is a strong mismatch to your actual headset pose.

**Comment by bjornbytes** [comment]
This needs to be retested on the miniaudio branch, but I think the race condition will still exist, since the listener pose is still being set twice in a frame.

One possibility is to close this as wontfix and have people modify boot.lua, but I don't think that's very friendly.  Something slightly more friendly would be to add a conf.lua flag that disables the automatic call to `lovr.audio.setPose`.  Another option would be to simply not synchronize the listener pose with the head pose.  That last option actually feels like the most "lovely" approach.  I am reminded of this quote from rude:

> It's really easy to create a high level component which seems nice, but in reality is too inflexible for many cases, leaving lovers to develop their own e.g. tilemap component anyway, feeling sad that the built-in component is just uselessly standing there.

LOVR trying to be helpful by setting the listener pose for you seems like it is causing lovrers to feel sad.  If you already have to set the poses for all your Source objects, you may as well set the listener pose too and have full control over it, without any of the problems that come from someone else trying to do it for you.

The final "bombard the problem with technology" solution would be to add some system for "committing" or "presenting" audio changes.  This would have a lot of benefits, and with some clever atomic sparkles this may even allow the mutex in the audio callback to be removed.

**Comment by nevyn** [comment]
Yeahh, the argument that you have to set the source pos anyways is a strong one. Might as well set listener too. (Which is annoying, I really like having good defaults)

**Comment by jmiskovic** [comment]
LOVR can only set listener pose in simple roomscale projects. As soon as one uses teleporting or any other mechanics that decouples VR world origin from headset tracking origin the pose that is set by LOVR will not be correct. Sure the conf flag would work but I'd prefer simpler model where updating source and listener poses is always user responsibility.

As for "commiting" changes, this is I think more of underlying mechanism and shouldn't impact the API. It makes sense to only set pose once per update so all setters can be cached and applied (flushed) at end of update. Maybe I misunderstood this part?

**Comment by bjornbytes** [comment]
Okay, the listener pose is no longer automatically set.

The committing system likely wouldn't impact the API, but there may need to be a secret `lovr.audio.commit` function similar to `lovr.math.drain` for it.
