### ISSUE TITLE
Occlusion Culling in a mesh

### ISSUE THREAD

**Issue by oilboi** [bjornbytes/lovr#277]
Would there be a way to implement occlusion culling in a mesh or globally so that things that are blocked are not rendered at all?

**Comment by bjornbytes** [comment]
It's pretty hard for LÖVR to do this automatically since it doesn't have complete control over how rendering works.  AABBs of Meshes aren't computed right now, for example, and even though Models know their AABB it can be inaccurate due to things like skeletal animation.  Also, Shaders can apply arbitrary transformations to vertices which would break frustum culling and occlusion culling, so there would need to be a way to disable it or some flag like "I promise my shaders use the built in camera".

So while it's not *impossible*, and might be added in the future, it's a tricky topic.  I'd probably welcome a pull request that implemented this, but the approach I'd probably take is to start off with a Lua implementation where it can be more easily customized.  LÖVR already gives you all the tools you need to implement it.
