### ISSUE TITLE
Overview of engine ideas

### ISSUE THREAD

**Issue by karai17** [bjornbytes/lovr#28]
I felt like it was worth writing these up on GitHub as opposed to leaving the throughts in the eternal history of the Slack channel.

The general idea listed here is to tirn LOVR into an opinionated engine instead of a loose framework. The purpose of this would be to allow developers to spend virtually (heh) all of their time in VR instead of constantly cycling your headset on and off of your face.

## Features

1. Integrate ImGui directly into LOVR
1. Build an extendable editor that is accessable in-game
1. Integrate and enforce an ECS code style
1. Integrate a Node (Blueprints) system that allows for code execution and generation (glsl, lua, json...)
1. Ability to hot-reload a game world

## Pros

1. Having a debug UI system such as ImGui built right into the engine would make life a lot easier for developers.
1. Having an in-game editor would really increase productivity and help developers better understand their data and how it's working in real time. Allowing developers to extend the editor to suite their needs would be really handy too.
1. ECS style has become very popular for gamedev. All major engines (Unreal, Unity, Cryengine) use (and enforce) some flavour of ECS.
1. Using an ECS system makes game code more predictable and more reusable and sharable. Example: The Unity Asset Store allows you to download pre-built scripts (pseudo-systems) that will "Just Work" in most games. Having this reusable and sharable code within the community would be really nifty.
1. Creating shaders, templates, even game logic with node groups is super handy. If designed properly, these node groups coudl also be a sharable asset like systems.
1. Restart your game withotu having to close and reload it is just plain nice. With carefully designed systems in place (such as the nodes, ECS, and other related things), refreshing major sections of a running game would be predictable and reliable.

## Cons

1. Depending on another dll/so file + increasing the final binary/release size is not something to do lightly. Ensuring a real need is there is definitely worth investigating before bloating LOVR with more stuff. This includes integrating dependencies (ImGui) or adding features (built-in editor, nodes, etc)
1. Enforcing a specific code style might be seen by some as too controlling.
1. Without tightly designed mechanisms, hot reloading a game can corrupt data and lead to unpredictable behaviour and crashes.

## Conclusion

I think that the pros of having all of these cool features generally outweigh the cons that I was able to think up. Being told how to design your code by the engine might seem rude, but it is definitely the trend we're in. The only people I can see who that might turn away woudl be peopel who generally aren't willing to expirement and learn in the first place. "I do things my way, and only my way" is probably nto the kind of attitude you want to foster in the community (I am aware of the irony here).

**Comment by HeadClot** [comment]
Hey got a request for the ECS side of things. Would it be possible to get nested prefab support?
Example: A prefab within a prefab.

**Comment by karai17** [comment]
Can you give me an example of what you mean by this?

**Comment by HeadClot** [comment]
Hey @karai17 sure. 
So I am making the assumption you know what a Unity Prefab is. That is what I am basing this on. 
Lets say I have 3 prefabs and a generic script - 

A red bird, yellow bird and a crocodile. Each are their own prefab.

The Crocodile is the top level prefab.
While the yellow bird and red bird are nested bellow the crocodile prefab.

Here is what the hierarchy looks like.
Crocodile (Prefab)
                 | - Red Bird (Prefab) (1 layer deep)
                 |---------- Yellow Bird (Prefab) (2 layers deep)
                 | - Generic Script (1 layer deep)

In unity this is not possible At the moment and it is really limiting. If LOVR supported this it would be really beneficial to making the engine a bit more flexible.

**Comment by karai17** [comment]
From @shakesoda on Slack:

```
the ecs has nothing to do with prefabs
prefabs would be a tree in the scene hierarchy, that flattens out when you get around to processing it with systems
(our engine works this way)
```

**Comment by frarf** [comment]
I have nothing to do with this framework, but this at least seems a bit out of what this framework is trying to do. Like love2d, this is a tiny framework that you build off of. Nothing more, nothing less. It isn't an engine.  
  
But even if I did like this idea, I have a few issues:  
  
* IMGUI? It seems like a weird choice since it's something primarily used for debugging and really rough interfaces, and it's 2D only. Having a 2D only framework is... manageable, but less than ideal. I really don't see the benefits here.  
  
* I see no advantage for a Blueprint-esque system to be integrated. Lua is fairly verbose, but I only feel that a node editor would make it more so. I feel like something like integrated Moonscript support would be neat and wouldn't boggle down development so much since Lua and Moonscript are two sides of the same coin.  
  
* Actually, the idea of a debug mode sounds pretty neat. Only problem is that this would require a prefab system, which I'm not entirely convinced sounds great. I am fond of some thing like a `lovr.debug` namespace existing.

Oh, side note, hotreloading can be solved by just holding a copy of the unchanged data, then loading in new data whenever you need to reload. If you want to save any changes (like the scene), you need to do this explicitly.  
  
Finally, I do think that LOVR is way to early in it's life cycle to consider transforming it into a game engine. It's come a very, very long way since even 6 months ago, but it still lacks some features vital for making games (like querying the physics world). This is cool, but unnecessary, at least at this point of time.

**Comment by karai17** [comment]
* IMGUI is great for debugging. WHile it is a 2D UI system, there is nothign stopping you from rendering it to a canvas and rendering that in 3D space. Are there other GUI libraries that are better suited for 3D?

* Nodes are super handy. You may not personally like them, but they are really good at doing a lot of different things. Designing AI systems, designing shaders, designing other types of systems, etc etc. You may not want to build a whole game with only nodes, but they do serve a very useful purpose.

I don't think timing is particularily important here. Having a quick and dirty framework you can use to get something on screen right away is definitely cool, but having built-in engine tools makes the middle and long term development cycle of your game go much smoother. It might be more immediately benefitial to the framework itself to get a few more checkboxes ticked, but I think if LOVR wants to be more than just a fun little toy, some of these bigger features shoudl at least be thought about now so they can be acted upon sooner rather than later.

**Comment by bjornbytes** [comment]
I'm going to close this since there hasn't been any activity for a while, and for now I'd like to keep things less opinionated.  Lately I've been having lots of related ideas about ways to better integrate developer niceties like hot reloading and VR debug overlays, but I think it's best to demonstrate success in external libraries and then integrate them into the core afterwards.
