### ISSUE TITLE
Leap motion hand tracking not working

### ISSUE THREAD

**Issue by CyberThund3r** [bjornbytes/lovr#290]
I can't get hand tracking to work with my leap motion, it works normally with other games/apps.
![OpenXR](https://i.imgur.com/UqYMxlb.png)
I'm still new to this but i checked for docs about it and couldn't find anything on it.
Am i missing something?

**Comment by bjornbytes** [comment]
The OpenXR driver isn't enabled by default right now and it needs to be explicitly enabled at compile time.  This is due to runtimes still having some issues, although things are improving rapidly and it's likely that OpenXR will be turned on by default soon.  For now, here is a build of `cbf168c` with OpenXR support.  I tested it with the `lovr-docs/examples/Interaction/Hand_Tracking` example and confirmed that it was working with Leap Motion.

[lovr-openxr.zip](https://github.com/bjornbytes/lovr/files/5367989/lovr-openxr.zip)
