### ISSUE TITLE
Quest 2 interop on desktop

### ISSUE THREAD

**Issue by newobj** [bjornbytes/lovr#386]
Hi, I suspect this is going to be a stupid issue on my end, but, I'm clueless as to how to diagnose it, so I was hoping you might be able to help. When I run the LOVR demos on a webpage, they run just fine in my HMD (Quest 2) when I click on the VR button in the corner of the window.

When I run LOVR.EXE locally against a hello world app, a window pops up on my desktop, but my HMD does nothing. (The same HMD that just worked fine showing the LOVR scene when it was being run from a web page.)

Oculus Link seems to be working fine otherwise. I'm on Windows. How can I figure out what's going on? I have no conf.lua and just pasted one of the tutorials into main.lua, which is behaving correctly in the desktop window. The HMD just does not recognize that a VR app is running it seems.

**Comment by bjornbytes** [comment]
The latest release came with the `openvr` and `desktop` drivers (desktop is the keyboard/mouse headset simulator).  You could see which driver is active by printing `lovr.headset.getDriver()` (might need to use `lovrc.bat` or pass the `--console` flag to see the output).

Does Oculus Link work with OpenVR?  If so, it should be possible to get it working.  Otherwise, I think you would need to use (compile with) the OpenXR or Oculus headset drivers.  I don't know much about Oculus Link so I'm really curious what the outcome is here.

**Comment by newobj** [comment]
Ok, so this was indeed user error. LOVR was giving me an error message on the console about not being to find openvr paths, which sure enough were absent on disk. Installing SteamVR seemed to put those things in place, and now LOVR works correctly running on the desktop! I had no clue I needed to install SteamVR to get OpenVR "drivers" (?) Thank you!
