### ISSUE TITLE
Pico Neo 3 Support

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#466]
Now I'm trying to build LOVR for Pico and discovered, that the Pico headset driver is completely broken. Build throws a lot of error. Especially, with methods, that unique for Pico and not used in vrapi driver.

**Comment by brainrom** [comment]
I'm experimenting with Pico Neo 3. The best result that now I can achieve is `org.lovr.app: The ClassLoaderContext is a special shared library.` And absolutely black screen.

**Comment by bjornbytes** [comment]
The Pico driver hasn't been tested on Neo 3 yet, so there could be some problems upgrading.  The reason pico can't use os_android is because pico's VR runtime owns a lot of system-related objects like the OpenGL context, main loop, etc.  So it can't use the normal os_android.c.

**Comment by brainrom** [comment]
Anyway, what about Lua-related errors, types conflicts? I've fixed it, and now headset_pico compiles. But `org.lovr.app: The ClassLoaderContext is a special shared library.` stays. How to debug this error? I think that problem is inside activity, not headset driver. Also searching over the Internet says, that is can be related to Android 10.

**Comment by bjornbytes** [comment]
Pushed a commit that fixes the pico build.  I don't remember seeing anything like the 'special shared library' issue when upgrading the Oculus build to Android 10.  Posting more logs might be useful, since I don't have a device to repro on right now.

**Comment by bjornbytes** [comment]
I wonder if the issue reproduces on a Pico Neo 2.

**Comment by brainrom** [comment]
```
Activity.java:16: error: Activity is not abstract and does not override abstract method deInitGL() in RenderInterface
public class Activity extends VRActivity implements RenderInterface, CVControllerListener {
       ^
1 error
```
added `public void deInitGL() {}` to activity. 

`adb -s PA7H10MGF5240020W shell am start org.lovr.app/org.lovr.app.Activity` 

`adb -s PA7H10MGF5240020W logcat -s org.lovr.app`:
```
 crash
--------- beginning of system
--------- beginning of main
08-05 15:35:40.293 28925 28925 E org.lovr.app: Not starting debugger since process cannot load the jdwp agent.
08-05 15:35:40.369 28925 28925 I org.lovr.app: The ClassLoaderContext is a special shared library.
08-05 15:35:45.375 28925 28956 I org.lovr.app: Waiting for a blocking GC ProfileSaver
08-05 15:35:45.381 28925 28956 I org.lovr.app: WaitForGcToComplete blocked ProfileSaver on AddRemoveAppImageSpace for 5.562ms
```

**Comment by brainrom** [comment]
I can provide you a remote ADB access to Pico Neo 3 for LOVR debugging every weekday from 06:00 to 15:00 UTC. Contact me via e-mail the day before remote access day if you interested in.

**Comment by nevyn** [comment]
There’s also some stuff around audio permissions that are stubbed out and not implemented :S it’s on my long todo… hopefully we can do something with openxr to merge pico and quest soon? Since both prefer openxr nowadays?

**Comment by bjornbytes** [comment]
Yes, Pico has since released an OpenXR runtime that is compatible with Pico Neo 3.  Since LÖVR is an OpenXR-compatible application, it _should_ just work with their runtime*.  However, it is not compatible with Neo 2 devices.  Are the people here primarily using Neo 2 or Neo 3?  I would love to replace the `pico` driver with the `openxr` driver since it is less code to maintain, the pico driver is kind of hacky, and their OpenXR runtime supports Vulkan!  But I wouldn't want to cause issues for people that are using LÖVR with Neo 2.

(*Side note: from what gathered by looking through their SDK and samples, their runtime is not 100% conformant with the OpenXR spec, so there will likely need to be changes made by either lovr or pico to get things to work properly with their hardware.  In my opinion, Pico should modify their runtime to comply with the OpenXR spec so that any OpenXR app will work on Pico, which is one of the motivating reasons for having a standard specification like OpenXR in the first place.  I started a discussion in the OpenXR Slack about this and some people from the working group said they're talking to Pico about it).

**Comment by bjornbytes** [comment]
Pico Neo 3 should be supported using their OpenXR SDK now.
