### ISSUE TITLE
Support for static audio sources

### ISSUE THREAD

**Issue by sophiabaldonado** [bjornbytes/lovr#47]
LÖVR already supports streams for audio sources. I would like to be able to get samples of an audio source which I think would require support of static audio sources. I'm basing this off of the love2d [Audio source constructor](https://love2d.org/wiki/love.audio.newSource) that accepts `'static'` and the [SoundData](https://love2d.org/wiki/SoundData) documentation with `SoundData:getSample(i)`.

**Comment by bjornbytes** [comment]
Ok so there are `SoundData` objects now that behave like LÖVE's SoundData.  The only difference is they are in the data module instead of the sound module, so you can create one with `lovr.data.newSoundData('file.ogg')`.  You can also create sources from them or pass 'static' as the second argument to `newSource`.  I'm still testing them out but there should be enough there to start messing around with.
