### ISSUE TITLE
lovr.graphics.print() fails with misleading error if you print more than ~13000 characters

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#483]
While constructing a test, I attempted to print a string of length 16146. This resulted in the error

> Whoa there!  Tried to get 80640 elements from a buffer that only has 65536 elements.

If I instead printed the substring containing the first 13122 characters, print() worked fine. (I assume this exact number is not important because probably spaces don't count toward your total.)

print() having a limit is fine. However,

1. The error message should clearly note that the problem is your string was too long, and ideally give some sort of hint of how many characters is too many.
2. It should be documented on lovr.org what the limit is.

**Comment by bjornbytes** [comment]
I think in this case `lovr.graphics.print` should do the loop for you, so long as it's comparable in complexity/overhead compared to not doing it.  Need to look into it.

We can probably catch the issue slightly earlier than trying to map the vertex buffer.  It's a little bit inconvenient to have every drawing function check for a triangle limit instead of doing it in one place, but not impossible.

Vulkan will have a higher limit here.

**Comment by mcclure** [comment]
I suspect the limit is actually a function of the glyphCount, and we calculate that in lovrGraphicsPrint (we call lovrFontMeasure) before we start mapping buffers, so maybe we could do it (either a loop or a limit) that way.

**Comment by bjornbytes** [comment]
Fun fact: the maximum number of sphere segments is 104
