### ISSUE TITLE
Adding Shapes to Colliders should recompute mass

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#490]
In #249, colliders with pre-attached shapes initialized their mass data properly.  However, adding new shapes to a collider doesn't adjust its mass, which can lead to weird center-of-mass/inertia tensor issues.

Mass should probably get recomputed when a shape is added/removed from a collider, or there should be a way to manually recompute mass from all attached shapes (the advantage of this would be you could add N shapes and then compute mass once instead of N times, but I don't think this is a particularly expensive operation so it might not matter).

LÖVE has `Body:resetMassData` (previously called `Body:setMassFromShapes`).

`dMassAdd` might be helpful.

**Comment by jmiskovic** [comment]
In my experience you don't really want your colliders to be offset from point of mass. It makes applying forces and torques harder. For instance, if you apply force with 3 axis components, the collider will start spinning because you applied it off center. To actually apply the force in mass center you'd have to fetch the local center and transform it into world coordinates. A bother, and not something we want to inflict on users.

On the other hand the `getLocalCenter()` will always return 0,0,0 because of this ODE's limitation so it's not useful at the moment.

**Comment by bjornbytes** [comment]
Adding/Removing/Moving/Changing shapes now recomputes mass by default.  Collider has `Collider:setAutomaticMass` which enables/disables this behavior.
