### ISSUE TITLE
Add Vec2, Vec3 and Quat constants

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#508]
Add constants with math objects for axes (for example, lovr.math.vec3.up, lovr.math.vec3.down, etc...), like it's done in Unity. It's should be useful during calculations.

**Comment by bjornbytes** [comment]
Good thing to start discussing.  If they were variables that held permanent vectors then they could be mutated, which is a problem.

- They could be functions that returns temp vectors.
- If a change is made to prevent mutation (#169) then this would work.
- I wonder if `lovr.math.vec2` can be the metatable instead of a function, then the constant versions could be accessed like `vec3.up` which would be nice.

**Comment by nevyn** [comment]
the constness of them seem like an orthogonal issue (heh). It would make the code more readable to just be able to say vec3.up instead of math.vec3(0,1,0). If it's implemented as temp vectors in __index today that's fine, and if as real constants in the future, that's great. that's my take at least :)

**Comment by ottworks** [comment]
__index seems like the cleanest way to make it work

**Comment by bjornbytes** [comment]
These are implemented on `dev`:

```lua
vec2.zero
vec2.one

vec3.zero
vec3.one
vec3.left
vec3.right
vec3.up
vec3.down
vec3.forward
vec3.back

vec4.zero
vec4.one

quat.identity
```

The `vec3` etc. tables are now the vector metatables with a `__call` metamethod, so it's also possible to add/override methods.
