### ISSUE TITLE
Plugin binary doesn't changes in bin when rebuilt

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#520]
When I change only plugin source code, plugin `.so` rebuilds in `plugins/lib` but in `bin` folder plugin's `.so` stays the same.

**Comment by bjornbytes** [comment]
This only reproduces on Linux.

**Comment by brainrom** [comment]
Ok, so I'll try to trace this issue on Linux.

**Comment by bjornbytes** [comment]
I'm trying to set up the CMake targets/commands to work properly.  So far I added a custom target named `lovr_plugins` that always builds, and then I added the commands to move the plugin libraries to build after `lovr_plugins` instead of `lovr`.  It seems to work, but I'm still just making sure there aren't any other issues and/or if it can be simplified.

**Comment by bjornbytes** [comment]
This is fixed now
