### ISSUE TITLE
Floating models

### ISSUE THREAD

**Issue by amansalted** [bjornbytes/lovr#523]
So I've been experimenting, especially with physics and noted that physics kinda floaty,
cannot really understand whether this intended or not? maybe I missing something?

**Comment by bjornbytes** [comment]
In the v0.15.0 build and earlier, friction was always infinite, but it was fixed in the master/dev releases.  So now the default is zero, making things a bit slippery (to work around this until the default friction is adjusted you can call :setFriction).  You can also try increasing the damping of colliders or the world's response time.  But without a specific example it's hard to say what the exact problem is.
