### ISSUE TITLE
Passing data-module types as argument to thread causes crash w/no error

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#524]
Create a sound with `lovr.data.newSound`. Pass it as an argument to `thread:start`.

In my tests (Windows, changeset date: Mon Sep 06 16:14:47 2021 -0700 |  summary:     Font:getWidth also returns width of last line;), download this sample:
[threadTest.zip](https://github.com/bjornbytes/lovr/files/7877994/threadTest.zip),
it crashes without printing an error message.

If I run in the debugger, I see the error message that got dropped:

![image](https://user-images.githubusercontent.com/277318/149679185-f6ea2e4d-ad51-449f-a126-6c56684c405e.png)

Talking to bjorn there appear to be two problems this reveals:

1. You can only pop something off a channel if you have included the module. But this is actually impossible if something is passed to thread:start
2. It appears that a properly thrown `lovrThrow`n message, if it occurs during the "C part" of thread:start startup, is not being printed.

I think (2) is more important than (1), I can switch from passing something as an arg to a channel, but I can only do this if the error message makes it clear I should do this

**Comment by bjornbytes** [comment]
Currently, when pushing an object in `_luax_pushtype`, `luaL_getmetatable` is used to get the metatable for the object's type.  If the metatable does not exist, an "unknown type" error is thrown.

Instead, `luaL_newmetatable` could be used, which returns the metatable if it already exists or otherwise creates it.  This would fix the "unknown type" error and allow objects to be passed as thread arguments.

However, there is some other info that goes into the metatable (destructor, tostring, etc.) that would be missing, so maybe we'd still need to wait for the module to be required before its types can be "finalized" and fully used.  I think it would be valid for userdata to be pushed to a thread's environment with "empty" metatables, then for code in the thread to do `require('lovr.data')` to fill in the metatables with valid info.

There's also a risk of allowing invalid types to be pushed, although I don't think this would come up in practice.

Regarding (2), I actually do get a decent error message for this:

> PANIC: unprotected error in call to Lua API (Unknown type 'Sound' (maybe its module needs to be required))

Maybe the windows console was being buffered or the --console argument was needed?  It would be possible to set a panic for the thread's Lua state but I'm not sure it would be much of an improvement over the default panic handler.

**Comment by bjornbytes** [comment]
I do want to acknowledge that some sort of improvement like

- Autocreating the lovr table in threads
- Autorequiring some modules in threads
- Allowing people to say which modules they want in their Thread when they create it

Would be a positive change, but in this case it wouldn't immediately fix the problem here -- there is more a "chicken and egg" problem related to modules needing to exist before objects can be pushed.

**Comment by bjornbytes** [comment]
This is fixed
