### ISSUE TITLE
If using adb push on Quest 2, conf.lua doesn't get read

### ISSUE THREAD

**Issue by KelseyHigham** [bjornbytes/lovr#533]
Here's a sample `conf.lua` that doesn't get read:
```lua
function lovr.conf(t)
    t.headset.supersample = 0.015625
    t.headset.msaa = 1
    t.modules.graphics = false
end
```

(Workaround: `conf.lua` does get read by [lodr](https://github.com/mcclure/lodr).)

**Comment by bjornbytes** [comment]
Another way to phrase this is that currently `conf.lua` can not be located in the save directory, since `lovr.boot` loads and runs the file before `lovr.filesystem.setIdentity` is called.  The identity normally *comes from* `lovr.conf`, so we have to do things in that order.

On Android though, the identity can not be changed and is always the package name.  So maybe that means Android can work different and mount the save directory earlier than other platforms.  It's a bit annoying to have special cases like that.

It's also good to consider if there are any "security" issues with allowing conf.lua to exist in the save folder.

**Comment by bjornbytes** [comment]
Maybe allow sourcing of conf.lua from the save directory when the apk is marked as debuggable?  (LÖVR APKs are debuggable by default, so this would basically allow adb push'd conf.luas to always work -- but still give people the option to prevent conf.lua from being tampered with in a release build).
