### ISSUE TITLE
lovr.html doesn't seem to work to deploy to the web

### ISSUE THREAD

**Issue by jtoy** [bjornbytes/lovr#549]
I am testing deploying to the web. I used /etc/lovr.html
I get this error:
```
lovr.html:68 Uncaught (in promise) TypeError: Module.FS_createPreloadedFile is not a function
    at lovr.html:68:18
    at callRuntimeCallbacks (lovr.js:1:21133)
    at preRun (lovr.js:1:9821)
    at run (lovr.js:1:181394)
    at runCaller (lovr.js:1:180731)
    at removeRunDependency (lovr.js:1:11107)
    at receiveInstance (lovr.js:1:12979)
    at receiveInstantiatedSource (lovr.js:1:13099)
```
which is this line: https://github.com/bjornbytes/lovr/blob/master/etc/lovr.html#L68

I tried with adding both https://lovr.org/static/f/v0.15.0/lovr.js
and 
https://lovr.org/static/f/v0.15.0/lovr.js
I tried this on the latest chrome and brave.
Is there a full working example we can play with?

I tried playing with the examples, but they seem to use some other format.
It would be helpful to link to a fully working example.

**Comment by jtoy** [comment]
Your instructions worked,  I think it is 2 things:
1) lovr.wasm file.  The distribution docs don't mention the wasm file and lovr.html has no mention of that file, so the docs will need to be cleaned up there. 
2) This line <script type="text/javascript" src="lovr.js"></script>, I had put this near the top, that doesnt work, it has to go at the bottom/replace {{{SCRIPT}}} , which the docs don't mention either. You mentioned a build system above, I haven't used that. Is the recommended way to use the build system or just do it by hand like I have done? 
3) One other thing, I didn't realize a webserver was needed, I was trying to load it locally, my bad. Might be good to clarify that. I don't recall needing a webserver when I was developing with p5js.

I can help clean up those docs.

For a self-contained web example , why not just put it in a subdirectory on lovr.org and link to it from the distribution docs. If that doesn't work, I would love to help host one if that is helpful.

Some other things I noticed:
* the app runs in the browser, but I get this in the console, should I be concerned:
  Warning: Could not load module "thread": module 'lovr.thread' not found:
```
lovr.js:1 	no field package.preload['lovr.thread']
lovr.js:1 	no file './lovr/thread.lua'
lovr.js:1 	no file '/usr/local/share/lua/5.1/lovr/thread.lua'
lovr.js:1 	no file '/usr/local/share/lua/5.1/lovr/thread/init.lua'
lovr.js:1 	no file '/usr/local/lib/lua/5.1/lovr/thread.lua'
lovr.js:1 	no file '/usr/local/lib/lua/5.1/lovr/thread/init.lua'
lovr.js:1 	no file './lovr/thread.so'
lovr.js:1 	no file '/usr/local/lib/lua/5.1/lovr/thread.so'
lovr.js:1 	no file '/usr/local/lib/lua/5.1/loadall.so'
lovr.js:1 	no file './lovr.so'
lovr.js:1 	no file '/usr/local/lib/lua/5.1/lovr.so'
lovr.js:1 	no file '/usr/local/lib/lua/5.1/loadall.so'
```
*  Single screen/non-vr mode works in the browser, yay! I was concerned it was not going to work.   Is it possible to dynamically turn this on/off while the app is running?
* lovr-keyboard and lovr-mouse can't be loaded in the browser,it fails with an error about not being supported. What is the recommended way to have code that will be cross-platform? Should the libraries add support or should we add a platform detection to dynamically load certain libraries? and how should keyboard/mouse work in a browser?

**Comment by bjornbytes** [comment]
I just pushed a [commit](https://github.com/bjornbytes/lovr-docs/commit/d678f59913f2c34dbda246aa572dddd3ca2222fc) to the lovr-docs repo that mentions the wasm file and the `{{{ SCRIPT }}}` template.

I intend on adding something like `lovr --package --web path/to/project` that will basically perform the steps described in this issue, but haven't prioritized that yet.

The build system is nice because it builds the lovr.js/lovr.wasm files and spits out a valid HTML file.  But compiling code isn't very friendly.

Regarding the warning about the thread module -- although threads are supported by the web target, the current build is not built with them enabled.   So the warning is innocuous, but could be suppressed by disabling the thread module in conf.lua:

```lua
function lovr.conf(t)
  t.modules.thread = false
end
```

That way, the thread module won't be loaded.

I don't understand the question about changing non-VR mode while the app is running.  If you're achieving it by disabling the headset module, that can't really be changed dynamically, although you could restart (`lovr.event.restart`) and somehow make conf.lua enable/disable the headset module.  If you're doing it by modifying some of the camera settings, it should be possible to change it dynamically.

lovr-keyboard and lovr-mouse use the FFI, which is a LuaJIT feature.  The web build doesn't use LuaJIT because LuaJIT can't be compiled for WebAssembly -- Lua is used instead there.  So any libraries using the FFI won't work.  There's some basic keyboard support in plain lovr now (`lovr.keypressed`, `lovr.keyreleased`, and `lovr.textinput` callbacks), but no mouse support (mice aren't really used in VR applications).

**Comment by jtoy** [comment]
yes, I was talking about disabling the headset module.  I was just wondering how that works.
For the keyboard and mouse, thanks for sharing that. I think longer term it would make sense to make a keyboard module that works across both desktop and web. For mouse, it would seem to be if it works on desktop, it would make sense to work in web as well, I see the use case of mostly for debugging. Since you already cleaned up some of the docs, let me know if there are any specific parts here that I could go work on, thanks!

**Comment by bjornbytes** [comment]
Ok, I'm going to close this since I think *most* of the issues here got ironed out.  Thanks for bringing all this up, these are some of the areas I would really like to improve and it's good to know when people are having trouble with them

**Comment by jtoy** [comment]
Great, I will just keep probing with questions as I play with lovr and I will make PRs later as I get more familiar with the code. Thank you for the awesome work @bjornbytes
