### ISSUE TITLE
AppVeyor doesn't know how to build Vulkan

### ISSUE THREAD

**Issue by mcclure** [bjornbytes/lovr#568]
Therefore all PRs against dev are currently failing, eg https://ci.appveyor.com/project/bjornbytes/lovr/builds/43991150 for #556

**Comment by bjornbytes** [comment]
Previously I've tried installing the Vulkan SDK in the appveyor script, but it timed out.  Since LÖVR only uses the headers, maybe KhronosGroup/Vulkan-Headers could be cloned instead (and CMake could be tricked into using that, or there could be an option to specify the Vulkan include path instead of using FindVulkan).  For glslangValidator, the standalone binary could be built from deps/glslang.  This would mean building glslang twice -- once for lovr and once for the standalone exe, unless CMake enables `ENABLE_GLSLANG_BINARIES`.

**Comment by bjornbytes** [comment]
appveyor can build the dev branch now.

**Comment by mcclure** [comment]
Cool
