### ISSUE TITLE
Add ability to resolve depth textures, where supported

### ISSUE THREAD

**Issue by eigenbom** [bjornbytes/lovr#621]
Texture samples default to 1, Render pass samples default to 4. I noticed this when receiving the "Sorry, resolving depth textures is not supported yet!" error, and wonder if they should both default to 1?

**Comment by bjornbytes** [comment]
If the textures have a sample count of 1, but the render pass sample count is 4, LÖVR internally creates temporary multisampled textures, renders to those, and "resolves" them to the target textures when the render pass is finished.  I think this is a sensible default, especially for VR.

There is definitely a wrinkle with depth textures right now though.  Core Vulkan messed up and didn't allow you to do resolves for depth textures.  When you are using an internal temporary depth buffer, everything works since no resolve is needed.  But if you pass your own depth texture, LÖVR can't do the resolve and gives you a gross error.

Vulkan quickly added an extension to let you do these depth resolves, and it's supported everywhere **except** unfortunately it still isn't supported on the Oculus Quest 1, which made me grumpy enough to not add support for it.  However, I could probably add support for this extension now, since the "dust has settled" with the Vulkan renderer and it's also much better at using extensions now.

Soooo, yeah, it's a long, complicated story.  It's good to call this out and track it, and there's probably an improvement that can be made to solve this (except for Quest 1).

**Comment by eigenbom** [comment]
Alright, sounds good. Thanks for explaining!

**Comment by bjornbytes** [comment]
This is implemented on the dev branch and will be included in the next release.
