### ISSUE TITLE
IOS Builds 

### ISSUE THREAD

**Issue by prakhar-s-srivastava** [bjornbytes/lovr#654]
Are there any plans on making this IOS compatible, The only thing stopping many ppl form using this is that no ios builds available

**Comment by bjornbytes** [comment]
There aren't any official plans at the moment.  iOS isn't a very prevalent platform for VR, and doesn't support OpenXR or WebXR (yet?).  If someone is really excited about running LÖVR on there and is able to implement/test, I'd definitely assist in integrating it into the framework though.

**Comment by SugarRayLua** [comment]
Hello!

With Apple's Vision Pro being released, are there any updated plans to consider portion LOVR to iOS?
I use Love on iOS which works pretty well and nice to collaborate on Love projects with Windows, Linux, and Mac users. However, Love's 3D libraries are only in their infancy, and it looks like LOVR already has 3D capabilities which would be nice to use on projects.

Thanks for the consideration. :-)

**Comment by bjornbytes** [comment]
Although the Vision Pro can run iOS apps, I think LÖVR would be more inclined to support Vision OS if possible.

**Comment by SugarRayLua** [comment]
Thanks for update! :-)

**Comment by salzig** [comment]
What would be needed to support the avp?

**Comment by bjornbytes** [comment]
I don't know much about Apple Vision Pro development, but from [this article](https://developer.apple.com/documentation/compositorservices/drawing_fully_immersive_content_using_metal) it seems like you can render arbitrary content with Metal, which would be a good fit for LÖVR.  MoltenVK should be able to take care of translating LÖVR's Vulkan calls to Metal.

Since AVP doesn't support OpenXR, LÖVR needs to add a new headset driver for it.  LÖVR currently has headset drivers for OpenXR, WebXR, and a keyboard/mouse simulator, each in a C file [here](https://github.com/bjornbytes/lovr/tree/dev/src/modules/headset).  The C API for a driver looks like [this](https://github.com/bjornbytes/lovr/blob/dev/src/modules/headset/headset.h#L146), although most of the methods are optional.  An AVP headset driver would probably call into ARKit (which has a [C API](https://developer.apple.com/documentation/arkit/arkit_in_visionos_c_api)?), CompositorServices, etc.

Overall I think it would be very painful to map these objective C APIs onto LÖVR's HeadsetInterface, but it's probably not impossible.  There are some alternative approaches I can think of as well:

- If someone developed a translation layer that was able to run OpenXR apps on the Apple Vision Pro, then LÖVR could support the device without significant changes.
- If Apple added support for OpenXR, then LÖVR would support it without significant changes.
- Since AVP supports WebXR, LÖVR could finish its WIP WebGPU renderer and add back WebXR support.  It's not as good as native support, but would still be nice to have.

If anyone knows more about AVP stuff, please correct me or add more info!

**Comment by coderofsalvation** [comment]
fwiw: no news about OpenXR, but webxr now works (no longer behind a browserflag), so I guess the webxr is safest bet.
Performancewise WebXR is better these days with XR (Projection)Layers, and its USP is top-notch distribution (via URL).

**Comment by nevyn** [comment]
As a visionOS developer, sounds about right Bjorn. Don't think you could access all the APIs you need through ObjC though, would require Swift. And a visionOS scaffold app, setting up an immersive space and renderer. And also Xcode deployment is not trivial. But it all seems doable!
