### ISSUE TITLE
Out of GPU memory when rapidly creating passes

### ISSUE THREAD

**Issue by brainrom** [bjornbytes/lovr#756]
App can work for some time, then crash with `GPU error: Out of GPU memory` message. Example are worked stable until e8e7c2afc1ec0703756f235a5db7c942d477ec68 (tested using `git bisect`). Tested on AMD RX570 and Intel i5-4210U integrated graphics. On AMD GPU (before and after e8e7c2afc1ec0703756f235a5db7c942d477ec68) I noticed GPU Memory usage spikes. Can this be related, that the passes, created with `lovr.graphics.newPass()` can't be released fast enough?

Example(with [lovr-ui](https://github.com/immortalx74/lovr-ui)):
```
UI = require "ui/ui"

function lovr.load()
    UI.Init()
end

function lovr.update()
    UI.InputInfo()
end

function lovr.draw( pass )
	UI.NewFrame( pass )
        UI.Begin( "FirstWindow", mat4( -0.5, 1.4, -1 ) )
        UI.Dummy(1,1)
	UI.End( pass )

	local ui_passes = UI.RenderFrame( pass )
	table.insert( ui_passes, pass )
	return lovr.graphics.submit( ui_passes )
end
```

**Comment by bjornbytes** [comment]
I pushed f93fb0c0c7a7dc816294d2bd3daefabd25cf4968 and 1cda2d59a7a40514ecd8a3aa050299bc0e816841 which help (lovr-ui no longer OOMs for me before your fix).  But yes, lovr-ui was creating passes too fast for GC to keep up with.  Each one used a 4MB block of memory for vertices, uniforms, etc., and there was a limit of 256 of those.

There might still be a few improvements that can be made so that the buffers can be recycled more eagerly, but hopefully it's not needed.

Thanks for issue koko :purple_heart:
