### ISSUE TITLE
Support gltf textures and animation

### ISSUE THREAD

**Issue by natebragg** [bjornbytes/lovr#764]
I attempted to open a `.gltf` that referenced associated `.png` files.  The model loaded, but the textures did not.  Likewise with the animation.

**Comment by bjornbytes** [comment]
How did you draw the Model?

**Comment by bjornbytes** [comment]
More info:

By default the Model is rendered in its setup pose, you can use `Model:animate` to play animations, see [this example](https://lovr.org/docs/Animation/Playback).

Also LÖVR's builtin shaders will only use the base color textures from the Model.  If you want to use the other PBR textures like metalness, roughness, emissive, etc. you'll need to use a custom shader.  There's a [PBR Materials example](https://lovr.org/docs/Lighting/PBR_Materials) which shows an example of doing that.

If you think there might be a bug with LÖVR, it would be helpful to post the Model you're using so that the developers can try loading it, better understand the problem, and fix it.

**Comment by natebragg** [comment]
I see!  I retract what I said about animation, thank you.  I am new to LÖVR and assumed that drawing the model would also animate it.  That said, as a newbie I'm overwhelmed by the PBR Materials example.  This does not seem to load the model's textures.  If I only call `setShader`, then it sets the model white, but including the `skybox` and `sphericalHarmonics` causes the error `No array texture layers give and cubemap face 'right' missing`.  I have a number of files `a.png`, `b.png`, etc., listed in the "images" key as a "uri".  How do I apply these?  Can this be done in a generic way without listing them explicitly?  I feel like it may benefit others if this were documented somewhere central, since I feel like opening a `.gltf` file should be "easy" (that is, doable for a newbie without having to digest the example you shared and modifying it to fit their project).

**Comment by bjornbytes** [comment]
I see, thanks for the info.

Models have multiple sub-meshes, and each can have a different material.  Materials have lots of different textures and properties in them, but out of the box LÖVR only renders the color texture.  The other textures are used for PBR lighting like in the sample, but lighting is highly app-specific so LÖVR doesn't try to handle it for you.

So if your Model is rendering as white where you expect there to be a color texture, this means the color textures aren't linked up properly in the glTF file.  Usually you would assign all the materials + textures in a modeling program and then import the asset into LÖVR, rather than linking up the textures after the fact.  So I'd try to edit the asset in e.g. Blender and re-import.

More lowlevel info on how the glTF asset is structured in case you're editing or debugging by hand: From the `images` array which you mentioned, look in the `textures` array for textures that have a `source` pointing at the index of the image you care about.  From *there*, you can look in the `materials` array for a material with `baseColorTexture` pointing at the index of the texture.  Then you can find a mesh in the `meshes` array that is using this material.  Maybe your meshes don't have materials assigned, or the materials don't have a baseColorTexture, etc.

Note: There is also a way to "override" the material that gets used by calling `Pass:setMaterial(texture)`, but this doesn't work well for Models with multiple sub-meshes since it will apply the same texture to all of the model's meshes.

**Comment by natebragg** [comment]
Hmm... that's interesting.  I just grabbed this model off of sketchfab for fun, I didn't make it myself.  I know zero about Blender or GLTF.  I tried another one, and it displayed somewhat but likewise had some issues.  Can you give a minimal example that loads and correctly displays [this file](https://sketchfab.com/3d-models/buster-drone-294e79652f494130ad2ab00a13fdbafd?ref=gltf_page) for example?

It would be very nice for newbies to have some sort of guide to have this work out of the box, without struggling with the internals of the file or having to write a bunch of code.  It's a wide departure from a hello world that loads an stl file, which takes 30 seconds to write, vs a gltf which feels like I need to be an advanced user.

**Comment by bjornbytes** [comment]
Here is a simple test with the model you linked:

```lua
local model = lovr.graphics.newModel('drone.glb')

function lovr.update(dt)
  model:animate(1, lovr.timer.getTime())
end

function lovr.draw(pass)
  pass:draw(model)
end
```

It renders the animated model with its base color textures applied:

![image](https://github.com/bjornbytes/lovr/assets/784805/dde0c2e4-434c-4897-bfd3-b143adc1945b)

This model was authored with several PBR textures: base color, emissive, metalness, roughness, ambient occlusion, and a normal map.  So it looks kinda weird with just the base color texture.  You can start to use a shader to incorporate some of the additional textures or apply lighting, here's a simple example that uses the getLighting helper, like in the PBR example:

```lua
local model = lovr.graphics.newModel('drone.glb')

local shader = lovr.graphics.newShader('unlit', [[
  vec4 lovrmain() {
    Surface surface = getDefaultSurface();
    vec3 lightDirection = vec3(0, -1, -1);
    vec4 lightColorAndBrightness = vec4(1, 1, 1, 5);
    float shadow = 1.;
    vec3 color = getLighting(surface, lightDirection, lightColorAndBrightness, shadow);
    return vec4(color, DefaultColor.a);
  }
]], { flags = { normalMap = true, tonemap = true } })

function lovr.update(dt)
  model:animate(1, lovr.timer.getTime())
end

function lovr.draw(pass)
  pass:setShader(shader)
  pass:draw(model)
end
```

![image](https://github.com/bjornbytes/lovr/assets/784805/1c6bdc49-5d93-4da9-bf53-34e6ff78b09c)

(Something seems to be going wrong with the emissive map here, the eye is blue instead of red, I think it's due to transparency)

**Comment by bjornbytes** [comment]
Also I agree that we should have better examples/guides for lighting, shadows, and materials!  It's something I want to work on but haven't prioritized yet.

**Comment by natebragg** [comment]
Very cool, thank you.  Is it a reasonable request to commit this as an example somewhere?  Or possibly even add part of that shader to LÖVR itself (like as an included shader out of the box) to make this code a bit cleaner?

**Comment by bjornbytes** [comment]
This was a built-in shader for a while, `standard`, but people didn't like it because it was difficult to customize.  So it was changed to the `getLighting` helper, which can be integrated into custom shaders more easily.  I suppose there could be still be a `standard` shader, but people would quickly need to switch to `getLighting` as soon as they want to change something.  It's more of the LÖVE/LÖVR philosophy to offer you the tools to do something yourself rather than try to do it for you (and inevitably end up doing a bad job at it).  (And honestly, so far this `getLighting` helper isn't really catching on, either, but maybe it just needs better docs).

Regarding an example: This is already supposed to be covered by the PBR Materials example.  That one is slightly more complicated since it also does image based lighting (with the skybox and spherical harmonics), so maybe you could make the case that there should be a "PBR Materials (Simple)" example or something.  Ideally there should be some accompanying guide that explains the background of what PBR lighting is all about, what `getLighting` is doing, etc.

If you want to make any small improvements to the docs you can click "Edit" on any page or submit a PR to the [lovr-docs](https://github.com/bjornbytes/lovr-docs) repository.

I'll close this now since hopefully it answers the original question and shows that it's more of a documentation issue. 
 I feel like I just need to drop everything for a few weeks and write a giant LÖVR guide about how to do 3D lighting since it does come up pretty frequently, but I haven't done that yet!

**Comment by natebragg** [comment]
Thanks for your diligent follow up.  This is a great project, I hope it flourishes.  After I get more comfortable I'll see if I can contribute somehow!
