### ISSUE TITLE
Commit 715edfd breaks controller button input for Monado Index Knuckles

### ISSUE THREAD

**Issue by SpookySkeletons** [bjornbytes/lovr#801]
I went through and tried some of the default demos in an attempt to see what's going on here and can verify lovr-playspace is troubled by this commit as well as all the documentation demos such as the cube drag https://lovr.org/docs/dev/Interaction/Dragging

Button input seemingly stopped working with this commit. I do not have any other controller types to test on me but I can recruit some community help if required.

**Comment by bjornbytes** [comment]
My understanding is that this is a [bug in monado](https://gitlab.freedesktop.org/monado/monado/-/issues/378).  LÖVR only adds the `XR_EXT_hand_interaction` action bindings if the extension is supported and enabled, and monado advertises support for this extension.

Lately I've been thinking of just disabling that extension if the runtime is monado, since it's been causing trouble for multiple people.

**Comment by bjornbytes** [comment]
OMG, nevermind, it was a typo!!!  Just pushed a fix.  Thanks for the issue
